info:
  contact: {}
paths:
  /api:
    get:
      consumes:
      - application/json
      description: Geting for welcome endpoint
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Welcome
swagger: "2.0"
